name: Check all YAML data files are valid

on: push

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      # set up correct version of node
      - id: nvmrc
        name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        name: Set up NodeJS
        with:
          node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'

      - run: yarn
        name: Install dependencies
      - name: Check all YAML data files are valid
        env:
          FORCE_COLOR: 3
          NPM_CONFIG_LOGLEVEL: silent
        run: yarn -s validate-data
